[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 1

[[main]]
  identifier = "archive"
  name = "Timeline"
  url = "timeline"
  weight = 2

# [[main]]
#   identifier = "posts"
#   name = "posts"
#   url = "posts"
#   weight = 3