# Site settings
title: "@hjwu" 
brief-intro: "想靠程式、數學活在這世界上的胖子"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hsinjungwu.github.io"

permalink: /:year-:month-:day-:title/

# other links
github_username:  hsinjungwu
email: hsinjungwu@gmail.com
linkedIn_username: hsinjungwu

description_footer: 前面的世界會更精彩。

# comments
# disqus_shortname:

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# url
category_dir: category/
tag_dir: tag/

timezone: Asia/Taipei

# excerpt
excerpt_separator: "<!-- more -->"

# paginate
paginate: 6

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jemoji
  - jekyll-mentions

katex_version: 0.11.1